# sudo docker container ls
version: '3'

services:

  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - AU

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - AU
#
#  redis:
#    container_name: redis
#    image: redis:latest
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#    environment:
#      - REDIS_PASSWORD=mystrongpassword
#
#  redis-ui:
#    container_name: redis-ui
#    image: redislabs/redisinsight:latest
#    ports:
#      - "8001:8001"
#    environment:
#      - REDISINSIGHT_FLASK_ENV=production
#    depends_on:
#      - redis

volumes:
  #  redis-data:
  postgres_data:
  pgadmin:

networks:
  AU:
    driver: bridge